#!/bin/bash
sudo install -m 755 ./translate /usr/local/bin
SHORTCUT=$(gsettings get org.gnome.settings-daemon.plugins.media-keys custom-keybindings | sed "s/\(@as \)*\[\(.*\)\]/\2/g" | tr "'" " ")
SHORTCUT_COUNT=$(echo $SHORTCUT | tr "," "\n" | wc -w)
NEW_SHORTCUT="/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom"
if (( SHORTCUT_COUNT == 0));
then
	NEW_SHORTCUT+=0/
	SHORTCUT=["'$NEW_SHORTCUT'"]
else
	NEW_SHORTCUT+=$SHORTCUT_COUNT/
	SHORTCUT+=', '$NEW_SHORTCUT
	SHORTCUT=["'$(echo $SHORTCUT | tr " , " "','")'"]
fi
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:$NEW_SHORTCUT name "Translate"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:$NEW_SHORTCUT command "translate"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:$NEW_SHORTCUT binding "<Super>t"
gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "$SHORTCUT"
